language: go
go:
  - 1.14.x
env:
  - GO111MODULE=on
install: true
script:
  - go test -v -mod=vendor ./...

  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-X github.com/bitgrip/cattlectl/internal/pkg/ctl.Version=${TRAVIS_TAG:-0.0.0-dev} -d -s -w -extldflags \"-static\"" -a -tags netgo -installsuffix netgo -mod=vendor -o build/cli/linux/cattlectl
  - tar czpvf build/cattlectl-${TRAVIS_TAG:-0.0.0-dev}-linux.tar.gz build/cli/linux/

  - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-X github.com/bitgrip/cattlectl/internal/pkg/ctl.Version=${TRAVIS_TAG:-0.0.0-dev} -s -w" -a -tags netgo -installsuffix netgo -mod=vendor -o build/cli/darwin/cattlectl
  - tar czpvf build/cattlectl-${TRAVIS_TAG:-0.0.0-dev}-darwin.tar.gz build/cli/darwin/

  - mkdir -p build/ansible/linux
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-X github.com/bitgrip/cattlectl/internal/pkg/ctl.Version=${TRAVIS_TAG:-0.0.0-dev} -d -s -w -extldflags \"-static\"" -a -tags netgo -installsuffix netgo -mod=vendor -o build/ansible/linux ./ansible/...
  - tar czpvf build/cattlectl-ansible-${TRAVIS_TAG:-0.0.0-dev}-linux.tar.gz build/ansible/linux/

  - mkdir -p build/ansible/darwin
  - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-X github.com/bitgrip/cattlectl/internal/pkg/ctl.Version=${TRAVIS_TAG:-0.0.0-dev} -s -w" -a -tags netgo -installsuffix netgo -mod=vendor -o build/ansible/darwin ./ansible/...
  - tar czpvf build/cattlectl-ansible-${TRAVIS_TAG:-0.0.0-dev}-darwin.tar.gz build/ansible/darwin/
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
    - build/cattlectl-${TRAVIS_TAG:-0.0.0-dev}-linux.tar.gz
    - build/cattlectl-${TRAVIS_TAG:-0.0.0-dev}-darwin.tar.gz
    - build/cattlectl-ansible-${TRAVIS_TAG:-0.0.0-dev}-linux.tar.gz
    - build/cattlectl-ansible-${TRAVIS_TAG:-0.0.0-dev}-darwin.tar.gz
  skip_cleanup: true
  on:
    repo: bitgrip/cattlectl
    tags: true
