---
api_version: v1.2
kind: Project
metadata:
  name: "{{ .project_name }}"
namespaces:
  - name: "{{ .project_name }}-web"
apps:
- name: blog-wordpress-from-values-yaml
  catalog: library
  chart: wordpress
  version: "2.1.10"
  namespace: "{{ .project_name }}-web"
  values_yaml: |
    {{readWithTemplate "app-values.yaml" | indent 2 | trim}}
